name: Build and Test Cartório C Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Listar arquivos no diretório (Debug)
        run: ls -R

      - name: Instalar Dependências
        run: sudo apt update && sudo apt install -y gcc

      - name: Compilar o Programa
        run: gcc -o cartorio Main/cartorio_.c -Wall -Wextra -pedantic

      - name: Testar Execução
        run: |
          ./cartorio <<EOF
          1
          Teste Nome
          123456
          5
          EOF
        timeout-minutes: 1
