name: Build and Test C Program

on: [push, pull_request]  # Executa o workflow a cada push ou pull request

jobs:
  build:
    runs-on: ubuntu-latest  # Usa uma máquina Linux com Ubuntu

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3  # Baixa o código do repositório

      - name: Instalar dependências
        run: sudo apt update && sudo apt install -y gcc  # Instala GCC para compilação

      - name: Compilar o Cartorio
        run: gcc -o servidor cartorio_.c -Wall -Wextra -pedantic -pthread -ljson-c  # Ajuste para sua necessidade

      - name: Testar Execução
        run: |
          ./cartorio      # Roda o cliente para testar a conexão
        timeout-minutes: 1  # Define um tempo máximo para o teste
