name: Build and Test Cartório C Project

on: [push, pull_request]  # Executa o workflow em cada push ou pull request

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliza uma máquina virtual com Ubuntu

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3  # Baixa o código do repositório

      - name: Instalar Dependências
        run: sudo apt update && sudo apt install -y gcc  # Instala GCC para compilação

      - name: Compilar o Programa
        run: gcc -o cartorio main.c -Wall -Wextra -pedantic  # Ajuste conforme necessário

      - name: Testar Execução
        run: |
          ./cartorio <<EOF
          1
          Teste Nome
          123456
          5
          EOF
        timeout-minutes: 1  # Define um tempo máximo para execução
